In [6]:
import pandas as pd
df= pd.read_csv('Attrition.csv')
df.head(4)

Age Attrition     BusinessTravel  DailyRate              Department  \
0   41       Yes      Travel_Rarely       1102                   Sales   
1   49        No  Travel_Frequently        279  Research & Development   
2   37       Yes      Travel_Rarely       1373  Research & Development   
3   33        No  Travel_Frequently       1392  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   
2                 2          2          Other              1               4   
3                 3          4  Life Sciences              1               5   

   ...  RelationshipSatisfaction StandardHours  StockOptionLevel  \
0  ...                         1            80                 0   
1  ...                         4            80                 1   
2  ...                         2            80                 0   
3  ...                         3            80                 0   

   TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  YearsAtCompany  \
0                  8                      0               1               6   
1                 10                      3               3              10   
2                  7                      3               3               0   
3                  8                      3               3               8   

  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager  
0                  4                        0                     5  
1                  7                        1                     7  
2                  0                        0                     0  
3                  7                        3                     0  

[4 rows x 35 columns]

In [8]:
df.shape

(1470, 35)

In [15]:
df.isnull()

Age  Attrition  BusinessTravel  DailyRate  Department  \
0     False      False           False      False       False   
1     False      False           False      False       False   
2     False      False           False      False       False   
3     False      False           False      False       False   
4     False      False           False      False       False   
...     ...        ...             ...        ...         ...   
1465  False      False           False      False       False   
1466  False      False           False      False       False   
1467  False      False           False      False       False   
1468  False      False           False      False       False   
1469  False      False           False      False       False   

      DistanceFromHome  Education  EducationField  EmployeeCount  \
0                False      False           False          False   
1                False      False           False          False   
2                False      False           False          False   
3                False      False           False          False   
4                False      False           False          False   
...                ...        ...             ...            ...   
1465             False      False           False          False   
1466             False      False           False          False   
1467             False      False           False          False   
1468             False      False           False          False   
1469             False      False           False          False   

      EmployeeNumber  ...  RelationshipSatisfaction  StandardHours  \
0              False  ...                     False          False   
1              False  ...                     False          False   
2              False  ...                     False          False   
3              False  ...                     False          False   
4              False  ...                     False          False   
...              ...  ...                       ...            ...   
1465           False  ...                     False          False   
1466           False  ...                     False          False   
1467           False  ...                     False          False   
1468           False  ...                     False          False   
1469           False  ...                     False          False   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                False              False                  False   
1                False              False                  False   
2                False              False                  False   
3                False              False                  False   
4                False              False                  False   
...                ...                ...                    ...   
1465             False              False                  False   
1466             False              False                  False   
1467             False              False                  False   
1468             False              False                  False   
1469             False              False                  False   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0               False           False               False   
1               False           False               False   
2               False           False               False   
3               False           False               False   
4               False           False               False   
...               ...             ...                 ...   
1465            False           False               False   
1466            False           False               False   
1467            False           False               False   
1468            False           False               False   
1469            False           False               False   

      YearsSinceLas

In [16]:
df.tail(3)

Age Attrition     BusinessTravel  DailyRate              Department  \
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
1467               3               6                  2   
1468               2               9                  6   
1469               4               4                  3   

      YearsSinceLastPromotion  YearsWithCurrManager  
1467                        0                     3  
1468                        0                     8  
1469                        1                     2  

[3 rows x 35 columns]

In [22]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   Age                       1470 non-null   int64 
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64 
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64 
 6   Education                 1470 non-null   int64 
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64 
 9   EmployeeNumber            1470 non-null   int64 
 10  EnvironmentSatisfaction   1470 non-null   int64 
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64 
 13  JobInvolvement            1470 non-null   int64 
 14  JobLevel                

In [25]:
df.describe()

Age    DailyRate  DistanceFromHome    Education  EmployeeCount  \
count  1470.000000  1470.000000       1470.000000  1470.000000         1470.0   
mean     36.923810   802.485714          9.192517     2.912925            1.0   
std       9.135373   403.509100          8.106864     1.024165            0.0   
min      18.000000   102.000000          1.000000     1.000000            1.0   
25%      30.000000   465.000000          2.000000     2.000000            1.0   
50%      36.000000   802.000000          7.000000     3.000000            1.0   
75%      43.000000  1157.000000         14.000000     4.000000            1.0   
max      60.000000  1499.000000         29.000000     5.000000            1.0   

       EmployeeNumber  EnvironmentSatisfaction   HourlyRate  JobInvolvement  \
count     1470.000000              1470.000000  1470.000000     1470.000000   
mean      1024.865306                 2.721769    65.891156        2.729932   
std        602.024335                 1.093082    20.329428        0.711561   
min          1.000000                 1.000000    30.000000        1.000000   
25%        491.250000                 2.000000    48.000000        2.000000   
50%       1020.500000                 3.000000    66.000000        3.000000   
75%       1555.750000                 4.000000    83.750000        3.000000   
max       2068.000000                 4.000000   100.000000        4.000000   

          JobLevel  ...  RelationshipSatisfaction  StandardHours  \
count  1470.000000  ...               1470.000000         1470.0   
mean      2.063946  ...                  2.712245           80.0   
std       1.106940  ...                  1.081209            0.0   
min       1.000000  ...                  1.000000           80.0   
25%       1.000000  ...                  2.000000           80.0   
50%       2.000000  ...                  3.000000           80.0   
75%       3.000000  ...                  4.000000           80.0   
max       5.000000  ...                  4.000000           80.0   

       StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
count       1470.000000        1470.000000            1470.000000   
mean           0.793878          11.279592               2.799320   
std            0.852077           7.780782               1.289271   
min            0.000000           0.000000               0.000000   
25%            0.000000           6.000000               2.000000   
50%            1.000000          10.000000               3.000000   
75%            1.000000          15.000000               3.000000   
max            3.000000          40.000000               6.000000   

       WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
count      1470.000000     1470.000000         1470.000000   
mean          2.761224        7.008163            4.229252   
std           0.706476        6.126525            3.623137   
min           1.000000        0.000000            0.000000   
25%           2.000000        3.000000            2.000000   
50%           3.000000        5.000000            3.000000   
75%           3.000000        9.000000            7.000000   
max           4.000000       40.000000           18.000000   

       YearsSinceLastPromotion  YearsWithCurrManager  
count              1470.000000           1470.000000  
mean                  2.187755              4.123129  
std                   3.222430              3.568136  
min                   0.000000              0.000000  
25%                   0.000000              2.000000  
50%                   1.000000              3.000000  
75%                   3.000000              7.000000  
max                  15.000000             17.000000  

[8 rows x 26 columns]

# selection and filtering

In [28]:
df['DailyRate'].head(10)


0    1102
1     279
2    1373
3    1392
4     591
5    1005
6    1324
7    1358
8     216
9    1299
Name: DailyRate, dtype: int64

# sorted and ranking


In [31]:
# df.sort_values(by='col')
df.sort_index()

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

In [32]:
df.rank()

Age  Attrition  BusinessTravel  DailyRate  Department  \
0     1025.5     1352.0           949.0     1038.0      1247.5   
1     1285.5      617.0           289.0      180.0       544.0   
2      823.5     1352.0           949.0     1343.5       544.0   
3      545.5      617.0           289.0     1362.0       544.0   
4      186.5      617.0           949.0      518.5       544.0   
...      ...        ...             ...        ...         ...   
1465   764.0      617.0           289.0      820.0       544.0   
1466   927.5      617.0           949.0      543.0       544.0   
1467   186.5      617.0           949.0       64.5       544.0   
1468  1285.5      617.0           289.0      970.0      1247.5   
1469   613.0      617.0           949.0      558.0       544.0   

      DistanceFromHome  Education  EducationField  EmployeeCount  \
0                104.5      311.5           330.5          735.5   
1                815.5       85.5           330.5          735.5   
2                314.0      311.5          1297.5          735.5   
3                461.5     1223.5           330.5          735.5   
4                314.0       85.5          1024.5          735.5   
...                ...        ...             ...            ...   
1465            1317.0      311.5          1024.5          735.5   
1466             662.0       85.5          1024.5          735.5   
1467             535.5      738.5           330.5          735.5   
1468             314.0      738.5          1024.5          735.5   
1469             815.5      738.5          1024.5          735.5   

      EmployeeNumber  ...  RelationshipSatisfaction  StandardHours  \
0                1.0  ...                     138.5          735.5   
1                2.0  ...                    1254.5          735.5   
2                3.0  ...                     428.0          735.5   
3                4.0  ...                     809.0          735.5   
4                5.0  ...                    1254.5          735.5   
...              ...  ...                       ...            ...   
1465          1466.0  ...                     809.0          735.5   
1466          1467.0  ...                     138.5          735.5   
1467          1468.0  ...                     428.0          735.5   
1468          1469.0  ...                    1254.5          735.5   
1469          1470.0  ...                     138.5          735.5   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                316.0              574.0                   27.5   
1                929.5              822.5                  918.0   
2                316.0              482.0                  918.0   
3                316.0              574.0                  918.0   
4                929.5              379.0                  918.0   
...                ...                ...                    ...   
1465             929.5             1168.0                  918.0   
1466             929.5              673.5                 1346.0   
1467             929.5              379.0                   27.5   
1468             316.0             1168.0                  918.0   
1469             316.0              379.0                  918.0   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                40.5           814.5               860.5   
1               871.0          1164.5              1096.5   
2               871.0            22.5               122.5   
3               871.0           982.5              1096.5   
4               871.0           279.0               487.5   
...               ...             ...                 ...   
1465            871.0           678.5               487.5   
1466            871.0           897.5              1096.5   
1467            871.0           814.5               487.5   
1468            252.5          1063.5               967.0   
1469           1394.0           525.5               741.0   

      Ye

# Handling missing values

In [33]:
df.isnull()

Age  Attrition  BusinessTravel  DailyRate  Department  \
0     False      False           False      False       False   
1     False      False           False      False       False   
2     False      False           False      False       False   
3     False      False           False      False       False   
4     False      False           False      False       False   
...     ...        ...             ...        ...         ...   
1465  False      False           False      False       False   
1466  False      False           False      False       False   
1467  False      False           False      False       False   
1468  False      False           False      False       False   
1469  False      False           False      False       False   

      DistanceFromHome  Education  EducationField  EmployeeCount  \
0                False      False           False          False   
1                False      False           False          False   
2                False      False           False          False   
3                False      False           False          False   
4                False      False           False          False   
...                ...        ...             ...            ...   
1465             False      False           False          False   
1466             False      False           False          False   
1467             False      False           False          False   
1468             False      False           False          False   
1469             False      False           False          False   

      EmployeeNumber  ...  RelationshipSatisfaction  StandardHours  \
0              False  ...                     False          False   
1              False  ...                     False          False   
2              False  ...                     False          False   
3              False  ...                     False          False   
4              False  ...                     False          False   
...              ...  ...                       ...            ...   
1465           False  ...                     False          False   
1466           False  ...                     False          False   
1467           False  ...                     False          False   
1468           False  ...                     False          False   
1469           False  ...                     False          False   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                False              False                  False   
1                False              False                  False   
2                False              False                  False   
3                False              False                  False   
4                False              False                  False   
...                ...                ...                    ...   
1465             False              False                  False   
1466             False              False                  False   
1467             False              False                  False   
1468             False              False                  False   
1469             False              False                  False   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0               False           False               False   
1               False           False               False   
2               False           False               False   
3               False           False               False   
4               False           False               False   
...               ...             ...                 ...   
1465            False           False               False   
1466            False           False               False   
1467            False           False               False   
1468            False           False               False   
1469            False           False               False   

      YearsSinceLas

In [34]:
df.notnull()

Age  Attrition  BusinessTravel  DailyRate  Department  \
0     True       True            True       True        True   
1     True       True            True       True        True   
2     True       True            True       True        True   
3     True       True            True       True        True   
4     True       True            True       True        True   
...    ...        ...             ...        ...         ...   
1465  True       True            True       True        True   
1466  True       True            True       True        True   
1467  True       True            True       True        True   
1468  True       True            True       True        True   
1469  True       True            True       True        True   

      DistanceFromHome  Education  EducationField  EmployeeCount  \
0                 True       True            True           True   
1                 True       True            True           True   
2                 True       True            True           True   
3                 True       True            True           True   
4                 True       True            True           True   
...                ...        ...             ...            ...   
1465              True       True            True           True   
1466              True       True            True           True   
1467              True       True            True           True   
1468              True       True            True           True   
1469              True       True            True           True   

      EmployeeNumber  ...  RelationshipSatisfaction  StandardHours  \
0               True  ...                      True           True   
1               True  ...                      True           True   
2               True  ...                      True           True   
3               True  ...                      True           True   
4               True  ...                      True           True   
...              ...  ...                       ...            ...   
1465            True  ...                      True           True   
1466            True  ...                      True           True   
1467            True  ...                      True           True   
1468            True  ...                      True           True   
1469            True  ...                      True           True   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                 True               True                   True   
1                 True               True                   True   
2                 True               True                   True   
3                 True               True                   True   
4                 True               True                   True   
...                ...                ...                    ...   
1465              True               True                   True   
1466              True               True                   True   
1467              True               True                   True   
1468              True               True                   True   
1469              True               True                   True   

      WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  \
0                True            True                True   
1                True            True                True   
2                True            True                True   
3                True            True                True   
4                True            True                True   
...               ...             ...                 ...   
1465             True            True                True   
1466             True            True                True   
1467             True            True                True   
1468             True            True                True   
1469             True            True                True   

      YearsSinceLastPromotion 

In [35]:
df.dropna() # remove the missing value

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

# aggregation function

In [39]:
df.sum()

Age                                                                     54278
Attrition                   YesNoYesNoNoNoNoNoNoNoNoNoNoNoYesNoNoNoNoNoNoY...
BusinessTravel              Travel_RarelyTravel_FrequentlyTravel_RarelyTra...
DailyRate                                                             1179654
Department                  SalesResearch & DevelopmentResearch & Developm...
DistanceFromHome                                                        13513
Education                                                                4282
EducationField              Life SciencesLife SciencesOtherLife SciencesMe...
EmployeeCount                                                            1470
EmployeeNumber                                                        1506552
EnvironmentSatisfaction                                                  4001
Gender                      FemaleMaleMaleFemaleMaleMaleFemaleMaleMaleMale...
HourlyRate                                                      

In [47]:
# create pivot table
# df.pivot_table(values,index,columns)

In [48]:
# df.rows()

# Data Transformations


In [52]:
# df.apply(func)
# df.map(func)
# df.replace(old,new)
# df.rename(columns={})

In [56]:
# df.astype(dtype)
# df.round(2)

In [57]:
df.index

RangeIndex(start=0, stop=1470, step=1)

# useful Utilities 

In [62]:
df.duplicated()


0       False
1       False
2       False
3       False
4       False
        ...  
1465    False
1466    False
1467    False
1468    False
1469    False
Length: 1470, dtype: bool

In [63]:
df.drop_duplicates()

Age Attrition     BusinessTravel  DailyRate              Department  \
0      41       Yes      Travel_Rarely       1102                   Sales   
1      49        No  Travel_Frequently        279  Research & Development   
2      37       Yes      Travel_Rarely       1373  Research & Development   
3      33        No  Travel_Frequently       1392  Research & Development   
4      27        No      Travel_Rarely        591  Research & Development   
...   ...       ...                ...        ...                     ...   
1465   36        No  Travel_Frequently        884  Research & Development   
1466   39        No      Travel_Rarely        613  Research & Development   
1467   27        No      Travel_Rarely        155  Research & Development   
1468   49        No  Travel_Frequently       1023                   Sales   
1469   34        No      Travel_Rarely        628  Research & Development   

      DistanceFromHome  Education EducationField  EmployeeCount  \
0                    1          2  Life Sciences              1   
1                    8          1  Life Sciences              1   
2                    2          2          Other              1   
3                    3          4  Life Sciences              1   
4                    2          1        Medical              1   
...                ...        ...            ...            ...   
1465                23          2        Medical              1   
1466                 6          1        Medical              1   
1467                 4          3  Life Sciences              1   
1468                 2          3        Medical              1   
1469                 8          3        Medical              1   

      EmployeeNumber  ...  RelationshipSatisfaction StandardHours  \
0                  1  ...                         1            80   
1                  2  ...                         4            80   
2                  4  ...                         2            80   
3                  5  ...                         3            80   
4                  7  ...                         4            80   
...              ...  ...                       ...           ...   
1465            2061  ...                         3            80   
1466            2062  ...                         1            80   
1467            2064  ...                         2            80   
1468            2065  ...                         4            80   
1469            2068  ...                         1            80   

      StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  \
0                    0                  8                      0   
1                    1                 10                      3   
2                    0                  7                      3   
3                    0                  8                      3   
4                    1                  6                      3   
...                ...                ...                    ...   
1465                 1                 17                      3   
1466                 1                  9                      5   
1467                 1                  6                      0   
1468                 0                 17                      3   
1469                 0                  6                      3   

     WorkLifeBalance  YearsAtCompany YearsInCurrentRole  \
0                  1               6                  4   
1                  3              10                  7   
2                  3               0                  0   
3                  3               8                  7   
4                  3               2                  2   
...              ...             ...                ...   
1465               3               5                  2   
1466               3               7                  7   
1467               3               6                  2   
1468               2               9    

In [65]:
df.memory_usage()

Index                         132
Age                         11760
Attrition                   11760
BusinessTravel              11760
DailyRate                   11760
Department                  11760
DistanceFromHome            11760
Education                   11760
EducationField              11760
EmployeeCount               11760
EmployeeNumber              11760
EnvironmentSatisfaction     11760
Gender                      11760
HourlyRate                  11760
JobInvolvement              11760
JobLevel                    11760
JobRole                     11760
JobSatisfaction             11760
MaritalStatus               11760
MonthlyIncome               11760
MonthlyRate                 11760
NumCompaniesWorked          11760
Over18                      11760
OverTime                    11760
PercentSalaryHike           11760
PerformanceRating           11760
RelationshipSatisfaction    11760
StandardHours               11760
StockOptionLevel            11760
TotalWorkingYe

In [71]:
df.sample()

Age Attrition BusinessTravel  DailyRate Department  DistanceFromHome  \
1188   29        No  Travel_Rarely        991      Sales                 5   

      Education EducationField  EmployeeCount  EmployeeNumber  ...  \
1188          3        Medical              1            1669  ...   

      RelationshipSatisfaction StandardHours  StockOptionLevel  \
1188                         2            80                 1   

      TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
1188                 10                      3               2   

      YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
1188              10                  0                        0   

      YearsWithCurrManager  
1188                     9  

[1 rows x 35 columns]

In [73]:
df.nunique()
df.value_counts()

Age  Attrition  BusinessTravel  DailyRate  Department              DistanceFromHome  Education  EducationField    EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  Gender  HourlyRate  JobInvolvement  JobLevel  JobRole                JobSatisfaction  MaritalStatus  MonthlyIncome  MonthlyRate  NumCompaniesWorked  Over18  OverTime  PercentSalaryHike  PerformanceRating  RelationshipSatisfaction  StandardHours  StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  YearsWithCurrManager
60   No         Travel_Rarely   1179       Sales                   16                4          Marketing         1              732             1                        Male    84          3               2         Sales Executive        1                Single         5405           11924        8                   Y       No        14                 3                  4                         80             0        

# numpy operations


In [74]:
# numpy is mathematica libaray in python that to performs the mathmetical opera


In [75]:
import numpy as np

In [76]:
np.array([1,2,3])

array([1, 2, 3])

In [83]:
np.zeros((2,4))
np.ones((4,4))

np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [84]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [106]:
# np.random.randint(2,40,10)
np.random.randn(2,3)



array([[-1.7112943 ,  0.33306028, -0.54151164],
       [ 1.32262937,  0.73790667, -0.14004631]])

In [108]:
np.empty((2,3))

array([[1.7112943 , 0.33306028, 0.54151164],
       [1.32262937, 0.73790667, 0.14004631]])

In [109]:
# Array Attributes of numpy

In [113]:
np.shape

<function shape at 0x000002CC7E8C86F0>

In [114]:
np.ndim

<function ndim at 0x000002CC7E8CA8B0>

In [118]:
np.size
np.dtype
# np.itemsize
# np.nbytes

numpy.dtype

# Reshaping and  modifying 

In [ ]:
a.reshape(3,2)
a.flatten()
a.ravel()
a.T
a.resize((2,6))
np.reshape(a,(2,3))

In [123]:
# #indexing and sizing
# a[0,1] #element 1 row 1 columns
# a[:,1]
# a[1:3,0:2]
# a[-1]
# a[::2] #step slicing

In [124]:
#comparison operations


In [132]:
a=10
b=22

# np.equal(a,b)
np.greater(b,a)
np.logical_and(a>2,b<10)

np.False_

In [136]:
a=[[1,2],
  [2,3]]
b=[[1,2],
  [2,3]]
np.dot(a,b)


array([[ 5,  8],
       [ 8, 13]])

In [137]:
np.matmul(a,b)

array([[ 5,  8],
       [ 8, 13]])

In [138]:
np.linalg.inv(a)

array([[-3.,  2.],
       [ 2., -1.]])

In [139]:
np.linalg.det(a)

np.float64(-1.0)

In [140]:
np.linalg.eig(a)

EigResult(eigenvalues=array([-0.23606798,  4.23606798]), eigenvectors=array([[-0.85065081, -0.52573111],
       [ 0.52573111, -0.85065081]]))

In [141]:
a.T

AttributeError: 'list' object has no attribute 'T'